/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author Windows Pro
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VolverPrincipi = new javax.swing.JButton();
        RegistroDeClientes = new javax.swing.JButton();
        BusquedaDeReservacion = new javax.swing.JButton();
        HistorialDeHabitacion = new javax.swing.JButton();
        CheckIn = new javax.swing.JButton();
        CheckOut1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VolverPrincipi.setBackground(new java.awt.Color(255, 255, 204));
        VolverPrincipi.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        VolverPrincipi.setText("VOLVER");
        VolverPrincipi.setBorder(null);
        VolverPrincipi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverPrincipiActionPerformed(evt);
            }
        });
        getContentPane().add(VolverPrincipi, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, 100, 40));

        RegistroDeClientes.setBackground(new java.awt.Color(255, 255, 204));
        RegistroDeClientes.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        RegistroDeClientes.setText("REGISTRO DE CLIENTES");
        RegistroDeClientes.setBorder(null);
        RegistroDeClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroDeClientesActionPerformed(evt);
            }
        });
        getContentPane().add(RegistroDeClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 290, 30));

        BusquedaDeReservacion.setBackground(new java.awt.Color(255, 255, 204));
        BusquedaDeReservacion.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BusquedaDeReservacion.setText("BÚSQUEDA DE RESERVACIÓN");
        BusquedaDeReservacion.setBorder(null);
        BusquedaDeReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaDeReservacionActionPerformed(evt);
            }
        });
        getContentPane().add(BusquedaDeReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 290, 30));

        HistorialDeHabitacion.setBackground(new java.awt.Color(255, 255, 204));
        HistorialDeHabitacion.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        HistorialDeHabitacion.setText("HISTORIAL DE HABITACIÓN");
        HistorialDeHabitacion.setBorder(null);
        HistorialDeHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialDeHabitacionActionPerformed(evt);
            }
        });
        getContentPane().add(HistorialDeHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 290, 30));

        CheckIn.setBackground(new java.awt.Color(255, 255, 204));
        CheckIn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        CheckIn.setText("CHECK IN");
        CheckIn.setBorder(null);
        CheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInActionPerformed(evt);
            }
        });
        getContentPane().add(CheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 290, 30));

        CheckOut1.setBackground(new java.awt.Color(255, 255, 204));
        CheckOut1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        CheckOut1.setText("CHECK OUT");
        CheckOut1.setBorder(null);
        CheckOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOut1ActionPerformed(evt);
            }
        });
        getContentPane().add(CheckOut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 290, 30));

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HOTEL BOOKING");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 470, 80));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("www.hotelbooking.com");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 190, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/19.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverPrincipiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverPrincipiActionPerformed
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverPrincipiActionPerformed

    private void RegistroDeClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroDeClientesActionPerformed
        BusquedaClientes busqueda = new BusquedaClientes();
        busqueda.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegistroDeClientesActionPerformed

    private void BusquedaDeReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaDeReservacionActionPerformed
        BusquedaReservación busqueda2 = new BusquedaReservación();
        busqueda2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BusquedaDeReservacionActionPerformed

    private void HistorialDeHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialDeHabitacionActionPerformed
        HistorialHabitacion historial = new HistorialHabitacion();
        historial.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HistorialDeHabitacionActionPerformed

    private void CheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInActionPerformed
        CheckIn check1 = new CheckIn();
        check1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CheckInActionPerformed

    private void CheckOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOut1ActionPerformed
        CheckOut check2 = new CheckOut();
        check2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CheckOut1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BusquedaDeReservacion;
    private javax.swing.JButton CheckIn;
    private javax.swing.JButton CheckOut1;
    private javax.swing.JButton HistorialDeHabitacion;
    private javax.swing.JButton RegistroDeClientes;
    private javax.swing.JButton VolverPrincipi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
